package ExceptionHandling;

public class tryExamples {

}
class try1{
	public static void main(String[] args) {
		int d,a;
		try {
			d=0;
			a = 34/d;
			System.out.println("This will not be Printed");
		}
		catch(ArithmeticException e) {
			System.out.println("Division by zero.");
		}
		System.out.println("After catch Statement");
	}
}